Fix compilation on Windows with /std:c++latest
When compiling libde265 on Windows using MSVC 2019 and the latest C++ standard preview (which is C++20), I get the following error:
`error C4496: nonstandard extension 'for each' used: replace with ranged-for statement`
The similar issue arises when using clang-cl.

Actually, MSVC supports ranged-for statement since MSVC 2012, and has full C++11 support for `auto` since MSVC 2015 (reference: https://docs.microsoft.com/en-us/previous-versions/hh567368(v=vs.140)?redirectedfrom=MSDN); `_MSC` version code for MSVC 2015 is `1900`. Hence the easy fix.